package com.antoniszisis.mywallet.ui.networth

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.antoniszisis.mywallet.data.repository.NetWorthRepository
import com.antoniszisis.mywallet.graphql.type.NetWorthEntryInput
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import java.time.LocalDate
import java.time.format.TextStyle
import java.util.Locale
import java.util.UUID
import javax.inject.Inject

val ASSET_CATEGORIES = listOf("Savings", "Investments", "Brokerage", "Retirement", "Crypto", "Real Estate", "Vehicle", "Other")
val LIABILITY_CATEGORIES = listOf("Mortgage", "Car Loan", "Student Loan", "Credit Card", "Personal Loan", "Other")

data class EntryDraft(
    val id: String = UUID.randomUUID().toString(),
    val type: String = "ASSET",
    val label: String = "",
    val amount: String = "",
    val category: String = ASSET_CATEGORIES.first(),
)

data class CreateSnapshotUiState(
    val title: String = generateSnapshotTitle(LocalDate.now()),
    val isTitleAutoGenerated: Boolean = true,
    val snapshotDate: LocalDate = LocalDate.now(),
    val showDatePicker: Boolean = false,
    val entries: List<EntryDraft> = listOf(EntryDraft()),
    val isCreating: Boolean = false,
    val error: String? = null,
)

fun generateSnapshotTitle(date: LocalDate): String =
    "${date.month.getDisplayName(TextStyle.FULL, Locale.getDefault())} ${date.year}"

@HiltViewModel
class CreateNetWorthSnapshotViewModel @Inject constructor(
    private val netWorthRepository: NetWorthRepository,
) : ViewModel() {

    private val _uiState = MutableStateFlow(CreateSnapshotUiState())
    val uiState = _uiState.asStateFlow()

    fun onTitleChange(title: String) {
        _uiState.value = _uiState.value.copy(
            title = title,
            isTitleAutoGenerated = false,
            error = null,
        )
    }

    fun onDateChange(date: LocalDate) {
        val state = _uiState.value
        _uiState.value = state.copy(
            snapshotDate = date,
            title = if (state.isTitleAutoGenerated) generateSnapshotTitle(date) else state.title,
            showDatePicker = false,
        )
    }

    fun showDatePicker() {
        _uiState.value = _uiState.value.copy(showDatePicker = true)
    }

    fun dismissDatePicker() {
        _uiState.value = _uiState.value.copy(showDatePicker = false)
    }

    fun addEntry(type: String) {
        val defaultCategory = if (type == "ASSET") ASSET_CATEGORIES.first() else LIABILITY_CATEGORIES.first()
        _uiState.value = _uiState.value.copy(
            entries = listOf(EntryDraft(type = type, category = defaultCategory)) + _uiState.value.entries,
        )
    }

    fun removeEntry(id: String) {
        if (_uiState.value.entries.size <= 1) return
        _uiState.value = _uiState.value.copy(
            entries = _uiState.value.entries.filter { it.id != id },
        )
    }

    fun updateEntry(id: String, update: EntryDraft.() -> EntryDraft) {
        _uiState.value = _uiState.value.copy(
            entries = _uiState.value.entries.map { if (it.id == id) it.update() else it },
        )
    }

    fun createSnapshot(onSuccess: () -> Unit) {
        val state = _uiState.value
        if (state.title.isBlank()) {
            _uiState.value = state.copy(error = "Title is required")
            return
        }
        val entriesInput = state.entries.mapNotNull { entry ->
            val amount = entry.amount.toDoubleOrNull()
            if (amount != null && amount > 0 && entry.label.isNotBlank()) {
                NetWorthEntryInput(
                    type = entry.type,
                    label = entry.label.trim(),
                    amount = amount,
                    category = entry.category,
                )
            } else null
        }
        if (entriesInput.isEmpty()) {
            _uiState.value = state.copy(error = "Add at least one entry with a label and amount greater than zero")
            return
        }
        viewModelScope.launch {
            _uiState.value = _uiState.value.copy(isCreating = true, error = null)
            netWorthRepository.createSnapshot(
                title = state.title.trim(),
                snapshotDate = state.snapshotDate.toString(),
                entries = entriesInput,
            ).fold(
                onSuccess = {
                    _uiState.value = _uiState.value.copy(isCreating = false)
                    onSuccess()
                },
                onFailure = { e ->
                    _uiState.value = _uiState.value.copy(
                        isCreating = false,
                        error = e.message ?: "Failed to create snapshot",
                    )
                }
            )
        }
    }
}
